# Generated by Django 4.2.7 on 2024-02-22 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='analysisreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision_class_0', models.FloatField(blank=True, null=True)),
                ('recall_class_0', models.FloatField(blank=True, null=True)),
                ('f1_class_0', models.FloatField(blank=True, null=True)),
                ('precision_class_1', models.FloatField(blank=True, null=True)),
                ('recall_class_1', models.FloatField(blank=True, null=True)),
                ('f1_class_1', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfusionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_positive', models.IntegerField()),
                ('true_negative', models.IntegerField()),
                ('false_positive', models.IntegerField()),
                ('false_negative', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='evaluationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision_class_0', models.FloatField(blank=True, null=True)),
                ('recall_class_0', models.FloatField(blank=True, null=True)),
                ('f1_class_0', models.FloatField(blank=True, null=True)),
                ('precision_class_1', models.FloatField(blank=True, null=True)),
                ('recall_class_1', models.FloatField(blank=True, null=True)),
                ('f1_class_1', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='SingleTrainFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Singlefiles')),
            ],
        ),
        migrations.CreateModel(
            name='StoredModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialized_model', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='StoredModel_scratch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialized_model', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='testfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Train_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat_Distance', models.FloatField(max_length=10)),
                ('Long_Distance', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
