# Generated by Django 4.2.7 on 2024-02-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_picklefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picklefile',
            old_name='file',
            new_name='Train_file',
        ),
    ]
