# Generated by Django 4.2.7 on 2024-02-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_remove_file_file_remove_picklefile_train_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Train_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
