# Generated by Django 4.2.7 on 2024-02-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_alter_file_train_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testfile',
            old_name='file',
            new_name='testFile',
        ),
    ]
