# Generated by Django 4.2.7 on 2024-02-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_logisticregressionconfusionmatrix_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleTrainFile',
        ),
    ]
