# Generated by Django 4.2.7 on 2024-02-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_delete_singletrainfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Train_data',
        ),
    ]
