# Generated by Django 4.2.7 on 2024-02-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSelected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.CharField(max_length=100)),
            ],
        ),
    ]
