# Generated by Django 4.2.7 on 2024-02-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_remove_picklefile_file_picklefile_text_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testfile',
            name='testFile',
        ),
        migrations.AddField(
            model_name='testfile',
            name='text_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
